environment:
  QTDIR: C:\Qt\5.7\msvc2015
  BOOST_ROOT: c:\Libraries\boost_1_60_0
  JAMOMA_ROOT: c:\projects\i-score\iscore-windows-sdk\jamoma

configuration: Release

image: Visual Studio 2015
platform: x86

install:
  - appveyor DownloadFile "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/unsis/nsis-2.46.5-Unicode-setup.exe" -FileName nsis.exe
  - nsis.exe /S

build_script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DISCORE_CONFIGURATION=release -DBOOST_ROOT="%BOOST_ROOT%" -DCMAKE_PREFIX_PATH="%QTDIR%/lib/cmake/Qt5" ..
  - msbuild PACKAGE.vcxproj /p:Configuration=Release /m
  - cmake --build . --target package

artifacts:
  - name: Installer
    path: 'build/i-score-*-win32.exe'

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  artifact: /.*\.exe/
  auth_token:
    secure: j0nBV9xVItdG3j6d0gHoyvrzi7TOhAy9/QIeyCbFeP8PTqq7DPr1oYwL5WIkPaXe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
